# Configuración de Conexión a Base de Datos Supabase (PostgreSQL)
db.host=aws-0-us-east-2.pooler.supabase.com
db.port=6543
db.name=postgres
db.user=postgres.ymfqanafhpayxvxvsrhw
db.password=parcialJava1
db.ssl=true
db.sslmode=require

# Configuración HikariCP Pool
pool.maximumPoolSize=10
pool.minimumIdle=2
pool.idleTimeout=30000
pool.connectionTimeout=20000
pool.maxLifetime=1800000
